CREATE TABLE IF NOT EXISTS `unitOfMeasurement` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ParentId` int(10) unsigned NOT NULL DEFAULT 0,
  `Name` tinytext NOT NULL DEFAULT '',
  `Unit` tinytext NOT NULL DEFAULT '',
  `Symbol` tinytext NOT NULL DEFAULT '',
  `Countable` bit(1) NOT NULL DEFAULT b'0',
  `BaseUnit` int(11) unsigned DEFAULT NULL,
  `ConversionFactor` float DEFAULT NULL,
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `FK_unitOfMeasurement_unitOfMeasurement` (`BaseUnit`),
  CONSTRAINT `FK_unitOfMeasurement_unitOfMeasurement` FOREIGN KEY (`BaseUnit`) REFERENCES `unitOfMeasurement` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;

INSERT INTO `unitOfMeasurement` (`Id`, `ParentId`, `Name`, `Unit`, `Symbol`, `Countable`, `BaseUnit`, `ConversionFactor`) VALUES
	(1, 0, 'Resitance', 'Ohm', 'Ω', b'0', NULL, NULL),
	(2, 0, 'Voltage', 'Volt', 'V', b'0', NULL, NULL),
	(3, 0, 'Current', 'Ampere', 'A', b'0', NULL, NULL),
	(4, 0, 'Capacitance', 'Farad', 'F', b'0', NULL, NULL),
	(5, 0, 'Inductance', 'Henry', 'H', b'0', NULL, NULL),
	(6, 0, 'Length', 'Meter', 'm', b'1', NULL, NULL),
	(7, 0, 'Power', 'Watt', 'W', b'0', NULL, NULL),
	(8, 0, 'Frequency', 'Herz', 'Hz', b'0', NULL, NULL),
	(9, 0, 'Temperatur', 'Degrees Celsius', '°C', b'0', NULL, NULL),
	(10, 0, 'Angle', 'Degrees', '°', b'0', NULL, NULL),
	(11, 0, 'Area', 'Square Meter', 'm2', b'1', NULL, NULL),
	(12, 0, 'Force', 'Newton', 'N', b'0', NULL, NULL),
	(13, 0, 'Weight', 'Gram', 'g', b'1', NULL, NULL),
	(14, 0, 'Magnetic Field Strength', 'Tesla', 'T', b'0', NULL, NULL),
	(15, 0, 'Bit', 'Bit', 'b', b'0', NULL, NULL),
	(16, 0, 'Byte', 'Byte', 'B', b'0', NULL, NULL),
	(18, 0, 'Ratio', 'Percent', '%', b'0', NULL, NULL),
	(19, 0, 'Ratio', 'Permil', '‰', b'0', NULL, NULL),
	(20, 0, 'Ratio', 'Parts Per Million', 'ppm', b'0', NULL, NULL),
	(21, 0, 'Time', 'Second', 's', b'0', NULL, NULL),
	(22, 0, 'Time', 'Hour', 'h', b'0', NULL, NULL),
	(23, 0, 'Number', '', '', b'0', NULL, NULL),
	(24, 0, 'Count', '', '', b'0', NULL, NULL),
	(25, 0, 'Temperature Coefficient', '', 'ppm/°C', b'0', NULL, NULL),
	(26, 0, 'Transfer Rate', 'Bytes per Second', 'B/s', b'0', NULL, NULL),
	(27, 0, 'Text', '', '', b'0', NULL, NULL),
	(28, 0, 'Transfer Rate', 'Bits per Second', 'bit/s', b'0', NULL, NULL),
	(29, 0, 'Piece', 'Piece', 'pcs', b'1', NULL, NULL),
	(30, 0, 'Volume', 'Liter', 'l', b'1', NULL, NULL),
	(31, 0, 'Length', 'Feet', 'ft', b'1', 6, 0.3048)
;