CREATE TABLE `unitOfMeasurement` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Name` tinytext NOT NULL,
  `Unit` tinytext NOT NULL ,
  `Symbol` tinytext NOT NULL,
  `Countable` bit(1) NOT NULL DEFAULT b'0',
  `BaseUnit` int(11) unsigned DEFAULT NULL COMMENT 'Number will be converted to base unit',
  `ConversionFactor` float DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `FK_unitOfMeasurement_unitOfMeasurement` (`BaseUnit`),
  CONSTRAINT `FK_unitOfMeasurement_unitOfMeasurement` FOREIGN KEY (`BaseUnit`) REFERENCES `unitOfMeasurement` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

INSERT INTO `unitOfMeasurement` (`Id`, `Name`, `Unit`, `Symbol`, `Countable`, `BaseUnit`, `ConversionFactor`) VALUES
	(1, 'Resitance', 'Ohm', 'Ω', b'0', NULL, NULL),
	(2, 'Voltage', 'Volt', 'V', b'0', NULL, NULL),
	(3, 'Current', 'Ampere', 'A', b'0', NULL, NULL),
	(4, 'Capacitance', 'Farad', 'F', b'0', NULL, NULL),
	(5, 'Inductance', 'Henry', 'H', b'0', NULL, NULL),
	(6, 'Length', 'Meter', 'm', b'1', NULL, NULL),
	(7, 'Power', 'Watt', 'W', b'0', NULL, NULL),
	(8, 'Frequency', 'Herz', 'Hz', b'0', NULL, NULL),
	(9, 'Temperatur', 'Degrees Celsius', '°C', b'0', NULL, NULL),
	(10, 'Angle', 'Degrees', '°', b'0', NULL, NULL),
	(11, 'Area', 'Square Meter', 'm2', b'1', NULL, NULL),
	(12, 'Force', 'Newton', 'N', b'0', NULL, NULL),
	(13, 'Weight', 'Gram', 'g', b'1', NULL, NULL),
	(14, 'Magnetic Field Strength', 'Tesla', 'T', b'0', NULL, NULL),
	(15, 'Bit', 'Bit', 'b', b'0', NULL, NULL),
	(16, 'Byte', 'Byte', 'B', b'0', NULL, NULL),
	(18, 'Ratio', 'Percent', '%', b'0', NULL, NULL),
	(19, 'Ratio', 'Permil', '‰', b'0', NULL, NULL),
	(20, 'Ratio', 'Parts Per Million', 'ppm', b'0', NULL, NULL),
	(21, 'Time', 'Second', 's', b'0', NULL, NULL),
	(22, 'Time', 'Hour', 'h', b'0', NULL, NULL),
	(23, 'Number', '', '', b'0', NULL, NULL),
	(24, 'Count', '', '', b'0', NULL, NULL),
	(25, 'Temperature Coefficient', '', 'ppm/°C', b'0', NULL, NULL),
	(26, 'Transfer Rate', 'Bytes per Second', 'B/s', b'0', NULL, NULL),
	(27, 'Text', '', '', b'0', NULL, NULL),
	(28, 'Transfer Rate', 'Bits per Second', 'bit/s', b'0', NULL, NULL),
	(29, 'Piece', 'Piece', 'pcs', b'1', NULL, NULL),
	(30, 'Volume', 'Liter', 'l', b'1', NULL, NULL),
	(31, 'Length', 'Feet', 'ft', b'1', 6, 0.3048)
;