CREATE TABLE `renderer` (
	`Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` TINYTEXT NOT NULL,
	`Description` TEXT NOT NULL DEFAULT '',
	`Render` ENUM('Template','PHP') NOT NULL,
	`Language` ENUM('ZPL','ESCPOS','HTML') NOT NULL,
	`Tag` TINYTEXT NULL DEFAULT NULL COLLATE 'ascii_bin',
	`Variables` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'ascii_bin',
	`Code` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'ascii_bin',
	`Hight` DECIMAL(6,2) NOT NULL DEFAULT '0.00',
	`Width` DECIMAL(6,2) NOT NULL DEFAULT '0.00',
	`Rotation` ENUM('0','90','180','270') NOT NULL DEFAULT '0',
	`Resolution` ENUM('6dpmm','8dpmm','12dpmm','24dpmm') NULL DEFAULT NULL,
	PRIMARY KEY (`Id`),
	UNIQUE KEY `Name` (`Name`)
);
