CREATE TABLE `vendor_alias` (
	`Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`VendorId` INT(10) UNSIGNED NOT NULL,
	`Name` CHAR(50) NOT NULL,
	`Note` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`Id`),
	UNIQUE KEY `Name` (`Name`),
	INDEX `VendorId` (`VendorId`),
	CONSTRAINT `FK_vendor_alias_vendor` FOREIGN KEY (`VendorId`) REFERENCES `vendor` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
