CREATE DEFINER=`root`@`%` FUNCTION `workOrder_generateWorkOrderNumber`()
RETURNS int(11)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN

	DECLARE varYear INT DEFAULT YEAR(CURDATE());
	DECLARE varNo INT DEFAULT 001;
	DECLARE varLastWoNo INT DEFAULT 000;

	SELECT WorkOrderNumber INTO varLastWoNo FROM workOrder WHERE YEAR(CreationDate) = YEAR(CURDATE()) AND MONTH(CreationDate) = MONTH(CURDATE()) ORDER BY WorkOrderNumber DESC LIMIT 1;

	SET varNo = (varLastWoNo%1000)+1;

	RETURN ((varYear-2000)*1000)+varNo;
END