CREATE TABLE `manufacturerPart_series` (
	`Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Title` TINYTEXT NOT NULL,
	`Description` TINYTEXT NULL DEFAULT NULL,
	`VendorId` INT(10) UNSIGNED NOT NULL,
	`NumberTemplate` TINYTEXT NULL DEFAULT NULL,
	`ClassId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`DocumentIds` TEXT NULL DEFAULT NULL,
	`SeriesNameMatch` TEXT NULL DEFAULT NULL,
	`Parameter` TEXT NULL DEFAULT NULL,
	`VerifiedByUserId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`CreationUserId` INT(10) UNSIGNED NOT NULL,
	`CreationDate` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `FK_manufacturerPartSeries_vendor` (`VendorId`) USING BTREE,
	INDEX `FK_manufacturerPartSeries_partClass` (`ClassId`) USING BTREE,
	INDEX `FK_manufacturerPart_series_user` (`VerifiedByUserId`) USING BTREE,
	INDEX `FK_manufacturerPart_series_user_2` (`CreationUserId`) USING BTREE,
	CONSTRAINT `FK_manufacturerPartSeries_partClass` FOREIGN KEY (`ClassId`) REFERENCES `manufacturerPart_class` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_manufacturerPartSeries_vendor` FOREIGN KEY (`VendorId`) REFERENCES `vendor` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_manufacturerPart_series_user` FOREIGN KEY (`VerifiedByUserId`) REFERENCES `user` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_manufacturerPart_series_user_2` FOREIGN KEY (`CreationUserId`) REFERENCES `user` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
