CREATE TABLE `assembly_unit_history` (
	`Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`AssemblyUnitHistoryNumber` INT(5) UNSIGNED ZEROFILL NOT NULL DEFAULT (cast(rand() * 100000 as signed)),
	`AssemblyUnitId` INT(10) UNSIGNED NOT NULL,
	`EditToken` CHAR(32) NULL DEFAULT NULL,
	`Title` TINYTEXT NOT NULL,
	`Description` TINYTEXT NULL DEFAULT NULL,
	`Data` LONGTEXT NULL DEFAULT NULL,
	`Type` ENUM('Unknown','Note','Production','Repair','Modification','Inspection Fail','Inspection Pass','Characterisation Test','Test Fail','Test Pass','Shipped Out','Firmware Change') NOT NULL DEFAULT 'Unknown',
	`Date` TIMESTAMP NOT NULL,
	`ShippingProhibited` BIT(1) NOT NULL DEFAULT b'0',
	`ShippingClearance` BIT(1) NOT NULL DEFAULT b'0',
	`CreationUserId` INT(10) UNSIGNED NOT NULL,
	`CreationDate` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`Id`),
	UNIQUE KEY `AssemblyUnitHistoryNumber` (`AssemblyUnitHistoryNumber`),
	UNIQUE KEY `EditToken` (`EditToken`),
	INDEX `FK_assembly_item_history_assembly_item` (`AssemblyUnitId`),
	INDEX `FK_assembly_unit_history_user` (`CreationUserId`),
	CONSTRAINT `FK_assembly_unit_history_assembly_unit` FOREIGN KEY (`AssemblyUnitId`) REFERENCES `assembly_unit` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_assembly_unit_history_user` FOREIGN KEY (`CreationUserId`) REFERENCES `user` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);