CREATE TABLE `purchaseOrder` (
	`Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`PurchaseOrderNumber` INT(10) UNSIGNED NOT NULL DEFAULT (cast(rand() * 100000 as signed)),
	`VendorId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`VendorAddressId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`VendorContactId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`ShippingContactId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`BillingContactId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`PurchaseContactId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`Carrier` TEXT NULL DEFAULT NULL,
	`PaymentTerms` TEXT NULL DEFAULT NULL,
	`InternationalCommercialTerms` TEXT NULL DEFAULT NULL,
	`HeadNote` TEXT NULL DEFAULT NULL,
	`FootNote` TEXT NULL DEFAULT NULL,
	`Spalte 26` TINYTEXT NULL DEFAULT NULL,
	`OrderNumber` TINYTEXT NULL DEFAULT NULL,
	`AcknowledgementNumber` TINYTEXT NULL DEFAULT NULL,
	`QuotationNumber` TINYTEXT NULL DEFAULT NULL,
	`Title` CHAR(150) NULL DEFAULT NULL,
	`PurchaseDate` DATE NOT NULL,
	`Description` MEDIUMTEXT NULL DEFAULT '',
	`Status` ENUM('Editing','Placed','Confirmed','Closed') NOT NULL DEFAULT 'Editing',
	`CurrencyId` INT(10) UNSIGNED NOT NULL DEFAULT '1',
	`ExchangeRate` FLOAT NOT NULL DEFAULT '1',
	`DocumentIds` TINYTEXT NULL DEFAULT NULL,
	`CreationUserId` INT(11) UNSIGNED NOT NULL,
	`CreationDate` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`Id`),
	UNIQUE KEY `PurchaseOrderNumber` (`PurchaseOrderNumber`),
	INDEX `FK_purchasOrder_finance_currency` (`CurrencyId`),
	INDEX `FK_purchasOrder_vendor` (`VendorId`),
	INDEX `FK_purchaseOrder_user` (`CreationUserId`),
	CONSTRAINT `FK_purchasOrder_finance_currency` FOREIGN KEY (`CurrencyId`) REFERENCES `finance_currency` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_purchasOrder_vendor` FOREIGN KEY (`VendorId`) REFERENCES `vendor` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_purchaseOrder_user` FOREIGN KEY (`CreationUserId`) REFERENCES `user` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
