CREATE TABLE `partStock` (
	`Id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`StockNumber` CHAR(4) NOT NULL,
	`ManufacturerPartNumberId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`SpecificationPartRevisionId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`AssemblyId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`Date` DATE NULL DEFAULT NULL,
	`CountryOfOriginCountryId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`LocationId` INT(11) UNSIGNED NOT NULL DEFAULT '1' COMMENT '1 -> "Unassigned"',
	`HomeLocationId` INT(11) NULL DEFAULT NULL,
	`CreationUserId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`CreationDate` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	`SupplierPartId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`ReceivalId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`LotNumber` CHAR(50) NULL DEFAULT NULL,
	`DeleteRequestUserId` INT(10) UNSIGNED NULL DEFAULT NULL,
	`DeleteRequestDate` TIMESTAMP NULL DEFAULT NULL,
	`DeleteRequestNote` TEXT NULL DEFAULT NULL,
	`CountingRequestUserId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`CountingRequestDate` TIMESTAMP NULL DEFAULT NULL,
	`Cache_Quantity` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`),
	UNIQUE KEY `StockNumber` (`StockNumber`),
	INDEX `FK_partStock_location` (`LocationId`),
	INDEX `FK_partStock_purchasOrder_itemReceive` (`ReceivalId`),
	INDEX `FK_partStock_user` (`DeleteRequestUserId`),
	INDEX `FK_partStock_manufacturerPart_partNumber` (`ManufacturerPartNumberId`),
	INDEX `FK_partStock_specificationPart_revision` (`SpecificationPartRevisionId`),
	INDEX `FK_partStock_user_2` (`CreationUserId`),
	INDEX `FK_partStock_assembly` (`AssemblyId`),
	INDEX `FK_partStock_user_3` (`CountingRequestUserId`),
	INDEX `FK_partStock_country` (`CountryOfOriginCountryId`),
	CONSTRAINT `FK_partStock_assembly` FOREIGN KEY (`AssemblyId`) REFERENCES `assembly` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_partStock_country` FOREIGN KEY (`CountryOfOriginCountryId`) REFERENCES `country` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_partStock_manufacturerPart_partNumber` FOREIGN KEY (`ManufacturerPartNumberId`) REFERENCES `manufacturerPart_partNumber` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_partStock_purchasOrder_itemReceive` FOREIGN KEY (`ReceivalId`) REFERENCES `purchaseOrder_itemReceive` (`Id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `FK_partStock_specificationPart_revision` FOREIGN KEY (`SpecificationPartRevisionId`) REFERENCES `specificationPart_revision` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_partStock_user` FOREIGN KEY (`DeleteRequestUserId`) REFERENCES `user` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_partStock_user_2` FOREIGN KEY (`CreationUserId`) REFERENCES `user` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_partStock_user_3` FOREIGN KEY (`CountingRequestUserId`) REFERENCES `user` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);