CREATE TABLE `inventory` (
	`Id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`PicturePath` MEDIUMTEXT NULL DEFAULT NULL,
	`InventoryNumber` INT(5) UNSIGNED ZEROFILL NOT NULL DEFAULT (cast(rand() * 100000 as signed)),
	`Title` MEDIUMTEXT NOT NULL,
	`InventoryCategoryId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`LocationId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`HomeLocationId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`VendorId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`Manufacturer` MEDIUMTEXT NULL DEFAULT NULL,
	`Type` MEDIUMTEXT NULL DEFAULT NULL,
	`Description` MEDIUMTEXT NULL DEFAULT NULL,
	`Note` MEDIUMTEXT NULL DEFAULT NULL,
	`DocumentIds` TINYTEXT NULL DEFAULT NULL,
	`SerialNumber` TINYTEXT NULL DEFAULT NULL,
	`AttributeList` LONGTEXT NULL DEFAULT NULL,
	`Status` ENUM('Normal','Broken','Scrapped') NOT NULL DEFAULT 'Normal',
	`CreationUserId` INT(10) UNSIGNED NOT NULL,
	`CreationDate` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`Id`),
	UNIQUE KEY `InventoryNumber` (`InventoryNumber`),
	INDEX `FK_equipment_location` (`LocationId`),
	INDEX `FK_equipment_equipmentCategory` (`InventoryCategoryId`),
	INDEX `FK_inventory_location` (`HomeLocationId`),
	INDEX `FK_inventory_vendor` (`VendorId`),
	INDEX `FK_inventory_user` (`CreationUserId`),
	CONSTRAINT `FK_inventory_inventoryCategories` FOREIGN KEY (`InventoryCategoryId`) REFERENCES `inventory_category` (`Id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `FK_inventory_location` FOREIGN KEY (`HomeLocationId`) REFERENCES `location` (`Id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `FK_inventory_locations` FOREIGN KEY (`LocationId`) REFERENCES `location` (`Id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `FK_inventory_user` FOREIGN KEY (`CreationUserId`) REFERENCES `user` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_inventory_vendor` FOREIGN KEY (`VendorId`) REFERENCES `vendor` (`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);