openapi: 3.0.0
info:
  title: "Blue Nova"
  version: 1.0.0

servers:
  - url: http://212.51.137.64/BlueNovaGCT/api.php
  
paths:
  /inventory:
    get:
        tags:
          - Inventory
        summary: Returns a list of the inventory items
        parameters:
          - name: InvNo
            in: query
            required: false
            description: Search for Inventory Numbers 
            schema:
              type: string
          - name: LocNr
            in: query
            required: false
            description: Filter for Location Numbers
            schema:
              type: string
          - name: Category
            in: query
            required: false
            description: Filter for category Name
            schema:
              type: string
        responses:
          '200':
            description: List of Inventory Items
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          PicturePath:
                            type: string
                            format: uri
                          InvNo:
                            type: string
                          Titel:
                            type: string
                          Manufacturer:
                            type: string
                          Type:
                            type: string
                          SerialNumber:
                            type: string
                          PurchaseDate:
                            type: string
                            format: date
                          PurchasePrice:
                            type: number
                            example: 12.49
                          SupplierName:
                            type: string
                          LocationName:
                            type: string
                    error:
                      type: string  
  /inventory/item:
    get:
        tags:
          - Inventory
        summary: Returns a list of the inventory items
        parameters:
          - name: InvNo
            in: query
            required: true
            description: Inventory item Number 
            schema:
              type: string
        responses:
          '200':
            description: Inventory Item Data
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: string
                    error:
                      type: string
                      
  /document:
    get:
        tags:
          - Documents
        summary: Returns a list of document
       
        responses:
          '200':
            description: Focument Types List
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          Description:
                            type: string
                          Type:
                            type: string
                          Path:
                            type: string
                            format: uri

                    error:
                      type: string
                      
  /document/type:
    get:
        tags:
          - Documents
        summary: Returns a list of document types
       
        responses:
          '200':
            description: Focument Types List
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: string

                    error:
                      type: string
  
  /document/item:
    get:
        tags:
          - Documents
        summary: Returns a Document
        parameters:
          - name: DocId
            in: query
            required: true
            description: Document Id Number 
            schema:
              type: string
        responses:
          '200':
            description: Inventory Item Data
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: string
                    error:
                      type: string
                      
                      
  /location:
    get:
      summary: Returns a list of locations
      tags:
        - Location
      responses:
          '200':
            description: List of Locations
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          Name:
                            type: string
                            format: uri
                          LocNr:
                            type: string
                          Children:
                            type: array
                            items:
                              type: object
                              properties:
                                Name:
                                  type: string
                                  format: uri
                                LocNr:
                                  type: string
                                Children:
                                  type: array
                                  items:
                                    type: string
                    error:
                      type: string                                   
  /inventory/category:
    get:
      summary: Returns a list of categories
      tags:
          - Inventory  
      responses:
          '200':
            description: List of Categories
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          Name:
                            type: string
                            format: uri
                          Id:
                            type: string
                          Children:
                            type: array
                            items:
                              type: object
                              properties:
                                Name:
                                  type: string
                                  format: uri
                                Id:
                                  type: string
                                Children:
                                  type: array
                                  items:
                                    type: string              
  /inventory/transfer:
    post:
      summary: Transfer a list of Inventory Items to a different location.
      tags:
          - Inventory  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                LocNr:
                  type: string
                ItemList:
                  type: array
                  items:
                    type: string

      responses:
          '200':
            description: List of Categories
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: string
                    error:
                      type: string  
  
  /supplier:
    get:
        tags:
          - Supplier
        summary: Returns a list of suppliers
       
        responses:
          '200':
            description: Supplier List
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: string

                    error:
                      type: string     
